//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb1_product
    {
        internal int pro_fk_user;

        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_image { get; set; }
        public string pro_des { get; set; }
        public Nullable<int> pro_price { get; set; }
        public Nullable<int> pro_fk_user1 { get; set; }
        public Nullable<int> pro_fk_cat { get; set; }
    
        public virtual tb1_user1 tb1_user1 { get; set; }
        public virtual tbl_category tbl_category { get; set; }
    }
}
